### ISSUE TITLE
BallotNav Home Page 

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#127]
### Overview
Users should have an engaging home page that is easy to understand. 

### User Acceptance Criteria 
- [ ] BallotNav logo should appear on the upper left hand side 
- [ ] Buttons for 'About' 
     - [ ] Links to page that tells user more about BallotNav 
- [ ] Button for 'Volunteer' 
    - [ ] Links to volunteer form at http://ballotnav.org/volunteer
- [ ] Button for 'Press' 
    - [ ] Links to press form 
- [ ] Button for 'Language' 
    - [ ] User should be able to toggle on Spanish translation 
- [ ] User should see informative language about BallotNav 
- [ ] search by address feature should function with a valid address 
    - [ ] invalid address? 
- [ ] Browse low bandwidth version text 
    - [ ] lets user navigate to low bandwidth site of Ballotnav
    - [ ] more information icon? 
- [ ] User should see static graphic 
- [ ] Connect to social media accounts 
    - [ ] Links to BallotNav official social media accounts #4 
- [ ] Share button feature 
- [ ] Copyright language 
- [ ] Link to Privacy Policy page #104 

### Individual Result Display Requirement 
- [ ] BallotNav logo 
- [ ] Search by address #42 
- [ ] Checkboxes for voting sequence 'Voting can be easy as 4 steps:' 
     - [ ] have you registered to vote 
     - [ ] have you applied for an absentee ballot 
     - [ ] use ballot nav to find your location 
- [ ] Browse low bandwidth version 

### Action Items
- [ ] Product
   - [ ] Determine home page layout 
   - [ ] Determine functionality of page 
   - [ ] Identify error handling requirements
- [ ] UI/UX
   - [ ] Make mockup of homepage: 
       - [ ] show user journey through homepage features 
- [ ] Front End Dev (React)
   - [ ] Build out homepage design spec 
- [ ] Back End Dev
   - [ ] api? 

### Resources/Instructions 
[Figma](https://www.figma.com/file/dvtVjMEBqj34a0tv5WEbMd/Ballotnav?node-id=344%3A3232)
[BallotNav 1-pager](https://docs.google.com/document/d/15tMTwUnPnfAeN1C4KP4mvGWaiz3IfkktTY4drKFa8eo/edit?usp=sharing)
