### ISSUE TITLE
Hello world

### ISSUE THREAD

**Issue by theswerd** [hackforla/ballotnav#30]
### Overview

Hello World Milestone requirements

### Action Items
- [x] #26  Basic Front End React + deck.gl
- [x] #27 Basic Flask + Docker + Docker Compose
- [x] #28  Basic Data structure
- [x] #29 CI
