### ISSUE TITLE
Product Roadmap

### ISSUE THREAD

**Issue by Arjayellis** [hackforla/ballotnav#34]
### Overview
We will create a roadmap to stay on track and ensure members are aware of necessary milestones 

### Action Items
- [x] Create roadmap document
- [x] Update milestones based on new requirements
- [x] Get feedback from stakeholders

### Resources/Instructions
- [Roadmap DRAFT](https://docs.google.com/spreadsheets/d/1vVo87ZO02xd_JyLDXDm6Q5EWRGKRzsl6Nj_Gt8Wl3wc/edit#gid=0)

**Comment by Arjayellis** [comment]
@myastark @kcoronel @jafow @salice Drafted a roadmap for the site in order to set expectations with the team and help us stay on pace. Will continue to build it over this week. Please feel free to add to your respective fields and make changes as necessary. https://docs.google.com/spreadsheets/d/1vVo87ZO02xd_JyLDXDm6Q5EWRGKRzsl6Nj_Gt8Wl3wc/edit#gid=0

**Comment by kcoronel** [comment]
@Arjayellis @allysmatrix I am thinking that our Product Roadmap should have a time frame so January - March, below is an example of January's work focus

Our first month will focus on developing our demo site on the repo which will help streamline the cost of hosting BallotNav site while still giving us an opportunity to introduce BallotNav to partners, funders, etc. As PM's we will coordinate the meeting between development and design to create frameworks for how the volunteer and admin page should look and function. Simultaneously, we will need to look at elections and match that up with our data, for example 
**_NYC Primary Elections June 22, 2021, 160 jurisdictions, average of 20 volunteers needed over 8 days _** helping us to outline a realistic timeline for launch 
We also need to begin auditing non-partisan nation, state, county voting organizations to enlist as partners

**Comment by Arjayellis** [comment]
@allysmatrix

**Comment by Arjayellis** [comment]
@kcoronel @allysmatrix 

We can now update the roadmap based on the new election choices. https://github.com/hackforla/ballotnav/issues/353

**Comment by allysmatrix** [comment]
I've made a few updates to the roadmap. And would like to talk thru it for further edits. Looks like June 8th is the next election we would have enough time to prepare for.
[https://docs.google.com/spreadsheets/d/1vVo87ZO02xd_JyLDXDm6Q5EWRGKRzsl6Nj_Gt8Wl3wc/edit#gid=961494988](url)
