### ISSUE TITLE
Usability Hub Test for Landing Page

### ISSUE THREAD

**Issue by Arjayellis** [hackforla/ballotnav#379]
### Overview
Conduct usability testing (using UsabilityHub) on the 3 options for landing page designs, to see if there's any iterations needed.

### Action Items
- [x] Create Usability Hub Profile for BallotNav 
- [x] Prototype landing page designs
- [x] Determine dates for testing 
- [x] Create testing that lets us see which design option is preferred by users on Usability Hub 
  - [x] Identify categories of users we want to make sure respond (i.e. folks outside of HackforLA) 
- [x] Synthesize results 
  - [x] Save user testing and results in drive [folder](https://drive.google.com/drive/folders/1qLfr5DROiitFqCsaUArNhMlJHKlUzH7E?usp=sharing)

### Resources/Instructions
[Prototype designs](https://www.figma.com/file/dvtVjMEBqj34a0tv5WEbMd/Ballotnav?node-id=1313%3A56178)

**Comment by Arjayellis** [comment]
@kcoronel @IrinaRost do we have final versions of the landing pages we can add to UHub?

**Comment by kcoronel** [comment]
@Arjayellis Irina, Jon, Federica, and I are meeting tomorrow to get our user test up and running

**Comment by kcoronel** [comment]
Landing Page Options 
<img width="1225" alt="Screen Shot 2021-03-26 at 7 11 52 AM" src="https://user-images.githubusercontent.com/38144130/112644498-b9031d80-8e02-11eb-9a86-2b7c441fd1ad.png">

**Comment by jonlam27** [comment]
**Phase 1:**

Testers: Hack for LA community

Two preference tests were created by @fedelandini 
1. Test A
- 3 landing page versions, which do you prefer?
- Any perceived political orientation?

2. Test B 
- 5 sec test of 3 landing page versions
- Rate from 1 to 5, the political orientation of each page

**Phase 2

Testers: Common voters

TBD - Navigation tests of preferred landing page

**Additional topics discussed:**
- Spanish version of BallotNav
- Accessibility of BallotNav

**Problems we noticed:** 
1. Free subscription of Usabilityhub
- prevents us from creating a test longer than 2 mins
- can't customize the welcome message so instructions for Test B will be provided separately

**Comment by kcoronel** [comment]
https://app.usabilityhub.com/do/7edaaf78f8fd/ea6 was launched on 3/29

**Comment by fedelandini** [comment]
28 responses

HP A  > 10      36%
HP B  > 8       29%
HP C  > 10     36%
Here a report of the test results. 
[BallotNav Test Results.docx](https://github.com/hackforla/ballotnav/files/6237133/BallotNav.Test.Results.docx)

**Comment by kcoronel** [comment]
Released second test on 4/6 
![Uploading Screen Shot 2021-04-06 at 4.16.49 PM.png…]()

**Comment by Arjayellis** [comment]
@kcoronel @fedelandini are we still working on the two versions 1) video first, 2) demo first? If not, can we get them posted this week?

**Comment by kcoronel** [comment]
@Arjayellis yes we are working on the next navigation test. Will update this comment with that navigation test once it is ready. For now, we have a new folder with the user navigation testing. 

We had 31 responses

**Comment by fedelandini** [comment]
Hi @Arjayellis I started to design this second version, but I stopped waiting for the second test result. I'm not available this week but I can have this done (design and test) for the next.

**Comment by kcoronel** [comment]
<img width="747" alt="Screen Shot 2021-04-13 at 1 46 58 PM" src="https://user-images.githubusercontent.com/38144130/114633469-5ff60f00-9c75-11eb-90ae-552d95d2b1bb.png">
