### ISSUE TITLE
Update BallotNav roadmap 

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#446]
### Overview
We need to land on an updates roadmap to prioritize the work to be done and to potentially recruit new members based on our identified needs. 

### Action Items
- [ ]  Draft the roadmap
- [ ]  Set up a team meeting with Eng and Design Leads to revise and approve the final roadmap (PM + Eng + Designers)
- [ ]  Finalise the roadmap
- [ ]  Link roadmap goals to milestones
- [ ]  Set up a revision cadence of the roadmap, eg: every 3 months

### Resources/Instructions
[2021 BallotNav - Roadmap](https://docs.google.com/spreadsheets/d/1vVo87ZO02xd_JyLDXDm6Q5EWRGKRzsl6Nj_Gt8Wl3wc/edit#gid=401267183)
[2022 BallotNav - Roadmap](https://docs.google.com/spreadsheets/d/1Lrzvsb7wy2qFHkVGYsVCPe2vcx4a-BUu2Kb3gRSHwc4/edit#gid=401267183)

**Comment by kcoronel** [comment]
Update 2/7: roadmap is ready for review with team

**Comment by kcoronel** [comment]
Please provide update
1. Progress : No updates to roadmap since team meeting on 2/7 
2. Blockers : None - but will be pausing until we determine North Star 
3. ETA: determine where to go in two weeks

**Comment by staceyrebekahscott** [comment]
Moving to prioritized backlog as no one is currently assigned, and other issues need to be completed before roadmap can be updated.
